module.exports = {
    '\\component': require('./component.json'),
    '\\component\\http': require('./component-http.json'),
    '\\component\\socket': require('./component-socket.json'),
    '\\component\\telegram\\bot': require('./component-telegram-bot.json'),
    '\\component\\telegram\\cli': require('./component-telegram-cli.json'),
    '\\database': require('./database.json'),
    '\\logger': require('./logger.json'),
    '\\npm': require('./npm.json'),
    '\\router\\http': require('./router-http.json'),
    '\\router\\socket': require('./router-socket.json'),
    '\\server': require('./server.json'),
    '\\service': require('./service.json'),
    '\\service\\http': require('./service-http.json'),
    '\\service\\instagram': require('./service-instagram.json'),
    '\\service\\socket': require('./service-socket.json'),
    '\\service\\telegram\\bot': require('./service-telegram-bot.json'),
    '\\service\\telegram\\cli': require('./service-telegram-cli.json'),
    '\\status': require('./status.json'),
};